services:
  - type: web
    name: softflow-website
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: softflow-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true

databases:
  - name: softflow-db
    plan: free